---

- name: Oracle JDK | Make sure openjdk is uninstalled
  apt: pkg=openjdk state=absent purge=true

- name: Oracle JDK | Add JRE ppa
  apt_repository: repo=ppa:webupd8team/java state=present
  sudo: yes

- name: Oracle JDK | Automatically select the Oracle License
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  sudo: yes

- name: Oracle JDK | Install apt requirements
  apt: state=present update_cache=yes pkg={{ item }} 
  with_items:
    - oracle-java7-installer
    - oracle-java7-set-default
  sudo: yes

